apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::912588832946:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HSY1S08CPRYF
      username: system:node:{{EC2PrivateDNSName}}
    -groups:
        - system:masters
        rolearn: arn:aws:iam::<912588832946>:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-30T11:02:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1629"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bf628fcd-39b5-4f1c-9e32-72d218d78542
